module.exports = {
	arrowParens: "avoid",
	bracketSpacing: true,
	endOfLine: "lf",
	htmlWhitespaceSensitivity: "strict",
	insertPragma: false,
	singleAttributePerLine: false,
	bracketSameLine: true,
	jsxBracketSameLine: false,
	jsxSingleQuote: false,
	printWidth: 80,
	proseWrap: "preserve",
	quoteProps: "as-needed",
	requirePragma: false,
	semi: true,
	singleQuote: false,
	tabWidth: 1,
	trailingComma: "es5",
	useTabs: true,
	embeddedLanguageFormatting: "auto",
	vueIndentScriptAndStyle: false,
	plugins: ["prettier-plugin-tailwindcss"],
	tailwindConfig: "./tailwind.config.js",
};
